// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: confidence/telemetry/v1/types/v1/types.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Confidence_Telemetry_V1_Platform: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case java // = 1
  case kotlin // = 2
  case swift // = 3
  case jsWeb // = 4
  case jsServer // = 5
  case python // = 6
  case go // = 7
  case ruby // = 8
  case rust // = 9
  case flutterIos // = 10
  case flutterAndroid // = 11
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .java
    case 2: self = .kotlin
    case 3: self = .swift
    case 4: self = .jsWeb
    case 5: self = .jsServer
    case 6: self = .python
    case 7: self = .go
    case 8: self = .ruby
    case 9: self = .rust
    case 10: self = .flutterIos
    case 11: self = .flutterAndroid
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .java: return 1
    case .kotlin: return 2
    case .swift: return 3
    case .jsWeb: return 4
    case .jsServer: return 5
    case .python: return 6
    case .go: return 7
    case .ruby: return 8
    case .rust: return 9
    case .flutterIos: return 10
    case .flutterAndroid: return 11
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Confidence_Telemetry_V1_Platform] = [
    .unspecified,
    .java,
    .kotlin,
    .swift,
    .jsWeb,
    .jsServer,
    .python,
    .go,
    .ruby,
    .rust,
    .flutterIos,
    .flutterAndroid,
  ]

}

struct Confidence_Telemetry_V1_MetricAnnotation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var unit: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Confidence_Telemetry_V1_Monitoring: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var libraryTraces: [Confidence_Telemetry_V1_LibraryTraces] = []

  var platform: Confidence_Telemetry_V1_Platform = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Confidence_Telemetry_V1_LibraryTraces: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var library: Confidence_Telemetry_V1_LibraryTraces.Library = .unknown

  var libraryVersion: String = String()

  var traces: [Confidence_Telemetry_V1_LibraryTraces.Trace] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum Library: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unknown // = 0
    case confidence // = 1
    case openFeature // = 2
    case react // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .unknown
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unknown
      case 1: self = .confidence
      case 2: self = .openFeature
      case 3: self = .react
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unknown: return 0
      case .confidence: return 1
      case .openFeature: return 2
      case .react: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Confidence_Telemetry_V1_LibraryTraces.Library] = [
      .unknown,
      .confidence,
      .openFeature,
      .react,
    ]

  }

  enum TraceId: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unknown // = 0
    case resolveLatency // = 1

    /// TODO deprecate?
    case staleFlag // = 2
    case flagEvaluation // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .unknown
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unknown
      case 1: self = .resolveLatency
      case 2: self = .staleFlag
      case 3: self = .flagEvaluation
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unknown: return 0
      case .resolveLatency: return 1
      case .staleFlag: return 2
      case .flagEvaluation: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Confidence_Telemetry_V1_LibraryTraces.TraceId] = [
      .unknown,
      .resolveLatency,
      .staleFlag,
      .flagEvaluation,
    ]

  }

  struct Trace: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var id: Confidence_Telemetry_V1_LibraryTraces.TraceId = .unknown

    var traceData: Confidence_Telemetry_V1_LibraryTraces.Trace.OneOf_TraceData? = nil

    /// DEPRECATED - Replaced by RequestTrace
    var millisecondDuration: UInt64 {
      get {
        if case .millisecondDuration(let v)? = traceData {return v}
        return 0
      }
      set {traceData = .millisecondDuration(newValue)}
    }

    var requestTrace: Confidence_Telemetry_V1_LibraryTraces.Trace.RequestTrace {
      get {
        if case .requestTrace(let v)? = traceData {return v}
        return Confidence_Telemetry_V1_LibraryTraces.Trace.RequestTrace()
      }
      set {traceData = .requestTrace(newValue)}
    }

    var countTrace: Confidence_Telemetry_V1_LibraryTraces.Trace.CountTrace {
      get {
        if case .countTrace(let v)? = traceData {return v}
        return Confidence_Telemetry_V1_LibraryTraces.Trace.CountTrace()
      }
      set {traceData = .countTrace(newValue)}
    }

    var evaluationTrace: Confidence_Telemetry_V1_LibraryTraces.Trace.EvaluationTrace {
      get {
        if case .evaluationTrace(let v)? = traceData {return v}
        return Confidence_Telemetry_V1_LibraryTraces.Trace.EvaluationTrace()
      }
      set {traceData = .evaluationTrace(newValue)}
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum OneOf_TraceData: Equatable, Sendable {
      /// DEPRECATED - Replaced by RequestTrace
      case millisecondDuration(UInt64)
      case requestTrace(Confidence_Telemetry_V1_LibraryTraces.Trace.RequestTrace)
      case countTrace(Confidence_Telemetry_V1_LibraryTraces.Trace.CountTrace)
      case evaluationTrace(Confidence_Telemetry_V1_LibraryTraces.Trace.EvaluationTrace)

    }

    struct CountTrace: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    struct RequestTrace: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var millisecondDuration: UInt64 = 0

      var status: Confidence_Telemetry_V1_LibraryTraces.Trace.RequestTrace.Status = .unspecified

      var unknownFields = SwiftProtobuf.UnknownStorage()

      enum Status: SwiftProtobuf.Enum, Swift.CaseIterable {
        typealias RawValue = Int
        case unspecified // = 0
        case success // = 1
        case error // = 2
        case timeout // = 3
        case cached // = 4
        case UNRECOGNIZED(Int)

        init() {
          self = .unspecified
        }

        init?(rawValue: Int) {
          switch rawValue {
          case 0: self = .unspecified
          case 1: self = .success
          case 2: self = .error
          case 3: self = .timeout
          case 4: self = .cached
          default: self = .UNRECOGNIZED(rawValue)
          }
        }

        var rawValue: Int {
          switch self {
          case .unspecified: return 0
          case .success: return 1
          case .error: return 2
          case .timeout: return 3
          case .cached: return 4
          case .UNRECOGNIZED(let i): return i
          }
        }

        // The compiler won't synthesize support with the UNRECOGNIZED case.
        static let allCases: [Confidence_Telemetry_V1_LibraryTraces.Trace.RequestTrace.Status] = [
          .unspecified,
          .success,
          .error,
          .timeout,
          .cached,
        ]

      }

      init() {}
    }

    struct EvaluationTrace: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var evaluationReason: Confidence_Telemetry_V1_LibraryTraces.Trace.EvaluationTrace.EvaluationReason = .unknown

      var unknownFields = SwiftProtobuf.UnknownStorage()

      enum EvaluationReason: SwiftProtobuf.Enum, Swift.CaseIterable {
        typealias RawValue = Int
        case unknown // = 0
        case success // = 1
        case stale // = 2
        case flagNotFound // = 3
        case typeMismatch // = 4
        case error // = 5
        case UNRECOGNIZED(Int)

        init() {
          self = .unknown
        }

        init?(rawValue: Int) {
          switch rawValue {
          case 0: self = .unknown
          case 1: self = .success
          case 2: self = .stale
          case 3: self = .flagNotFound
          case 4: self = .typeMismatch
          case 5: self = .error
          default: self = .UNRECOGNIZED(rawValue)
          }
        }

        var rawValue: Int {
          switch self {
          case .unknown: return 0
          case .success: return 1
          case .stale: return 2
          case .flagNotFound: return 3
          case .typeMismatch: return 4
          case .error: return 5
          case .UNRECOGNIZED(let i): return i
          }
        }

        // The compiler won't synthesize support with the UNRECOGNIZED case.
        static let allCases: [Confidence_Telemetry_V1_LibraryTraces.Trace.EvaluationTrace.EvaluationReason] = [
          .unknown,
          .success,
          .stale,
          .flagNotFound,
          .typeMismatch,
          .error,
        ]

      }

      init() {}
    }

    init() {}
  }

  init() {}
}

// MARK: - Extension support defined in types.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_EnumValueOptions {

  var Confidence_Telemetry_V1_metric: Confidence_Telemetry_V1_MetricAnnotation {
    get {return getExtensionValue(ext: Confidence_Telemetry_V1_Extensions_metric) ?? Confidence_Telemetry_V1_MetricAnnotation()}
    set {setExtensionValue(ext: Confidence_Telemetry_V1_Extensions_metric, value: newValue)}
  }
  /// Returns true if extension `Confidence_Telemetry_V1_Extensions_metric`
  /// has been explicitly set.
  var hasConfidence_Telemetry_V1_metric: Bool {
    return hasExtensionValue(ext: Confidence_Telemetry_V1_Extensions_metric)
  }
  /// Clears the value of extension `Confidence_Telemetry_V1_Extensions_metric`.
  /// Subsequent reads from it will return its default value.
  mutating func clearConfidence_Telemetry_V1_metric() {
    clearExtensionValue(ext: Confidence_Telemetry_V1_Extensions_metric)
  }

}

// MARK: - File's ExtensionMap: Confidence_Telemetry_V1_Types_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
let Confidence_Telemetry_V1_Types_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Confidence_Telemetry_V1_Extensions_metric
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

let Confidence_Telemetry_V1_Extensions_metric = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<Confidence_Telemetry_V1_MetricAnnotation>, SwiftProtobuf.Google_Protobuf_EnumValueOptions>(
  _protobuf_fieldNumber: 50641,
  fieldName: "confidence.telemetry.v1.metric"
)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "confidence.telemetry.v1"

extension Confidence_Telemetry_V1_Platform: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PLATFORM_UNSPECIFIED\0\u{1}PLATFORM_JAVA\0\u{1}PLATFORM_KOTLIN\0\u{1}PLATFORM_SWIFT\0\u{1}PLATFORM_JS_WEB\0\u{1}PLATFORM_JS_SERVER\0\u{1}PLATFORM_PYTHON\0\u{1}PLATFORM_GO\0\u{1}PLATFORM_RUBY\0\u{1}PLATFORM_RUST\0\u{1}PLATFORM_FLUTTER_IOS\0\u{1}PLATFORM_FLUTTER_ANDROID\0")
}

extension Confidence_Telemetry_V1_MetricAnnotation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MetricAnnotation"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}unit\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.unit) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.unit.isEmpty {
      try visitor.visitSingularStringField(value: self.unit, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Confidence_Telemetry_V1_MetricAnnotation, rhs: Confidence_Telemetry_V1_MetricAnnotation) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.unit != rhs.unit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Confidence_Telemetry_V1_Monitoring: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Monitoring"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}library_traces\0\u{1}platform\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.libraryTraces) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.platform) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.libraryTraces.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.libraryTraces, fieldNumber: 1)
    }
    if self.platform != .unspecified {
      try visitor.visitSingularEnumField(value: self.platform, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Confidence_Telemetry_V1_Monitoring, rhs: Confidence_Telemetry_V1_Monitoring) -> Bool {
    if lhs.libraryTraces != rhs.libraryTraces {return false}
    if lhs.platform != rhs.platform {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Confidence_Telemetry_V1_LibraryTraces: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LibraryTraces"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}library\0\u{3}library_version\0\u{1}traces\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.library) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.libraryVersion) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.traces) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.library != .unknown {
      try visitor.visitSingularEnumField(value: self.library, fieldNumber: 1)
    }
    if !self.libraryVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.libraryVersion, fieldNumber: 2)
    }
    if !self.traces.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.traces, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Confidence_Telemetry_V1_LibraryTraces, rhs: Confidence_Telemetry_V1_LibraryTraces) -> Bool {
    if lhs.library != rhs.library {return false}
    if lhs.libraryVersion != rhs.libraryVersion {return false}
    if lhs.traces != rhs.traces {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Confidence_Telemetry_V1_LibraryTraces.Library: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0LIBRARY_UNKNOWN\0\u{1}LIBRARY_CONFIDENCE\0\u{1}LIBRARY_OPEN_FEATURE\0\u{1}LIBRARY_REACT\0")
}

extension Confidence_Telemetry_V1_LibraryTraces.TraceId: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TRACE_ID_UNKNOWN\0\u{1}TRACE_ID_RESOLVE_LATENCY\0\u{1}TRACE_ID_STALE_FLAG\0\u{1}TRACE_ID_FLAG_EVALUATION\0")
}

extension Confidence_Telemetry_V1_LibraryTraces.Trace: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Confidence_Telemetry_V1_LibraryTraces.protoMessageName + ".Trace"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}millisecond_duration\0\u{3}request_trace\0\u{3}count_trace\0\u{3}evaluation_trace\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.id) }()
      case 2: try {
        var v: UInt64?
        try decoder.decodeSingularUInt64Field(value: &v)
        if let v = v {
          if self.traceData != nil {try decoder.handleConflictingOneOf()}
          self.traceData = .millisecondDuration(v)
        }
      }()
      case 3: try {
        var v: Confidence_Telemetry_V1_LibraryTraces.Trace.RequestTrace?
        var hadOneofValue = false
        if let current = self.traceData {
          hadOneofValue = true
          if case .requestTrace(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.traceData = .requestTrace(v)
        }
      }()
      case 4: try {
        var v: Confidence_Telemetry_V1_LibraryTraces.Trace.CountTrace?
        var hadOneofValue = false
        if let current = self.traceData {
          hadOneofValue = true
          if case .countTrace(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.traceData = .countTrace(v)
        }
      }()
      case 5: try {
        var v: Confidence_Telemetry_V1_LibraryTraces.Trace.EvaluationTrace?
        var hadOneofValue = false
        if let current = self.traceData {
          hadOneofValue = true
          if case .evaluationTrace(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.traceData = .evaluationTrace(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.id != .unknown {
      try visitor.visitSingularEnumField(value: self.id, fieldNumber: 1)
    }
    switch self.traceData {
    case .millisecondDuration?: try {
      guard case .millisecondDuration(let v)? = self.traceData else { preconditionFailure() }
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 2)
    }()
    case .requestTrace?: try {
      guard case .requestTrace(let v)? = self.traceData else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .countTrace?: try {
      guard case .countTrace(let v)? = self.traceData else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .evaluationTrace?: try {
      guard case .evaluationTrace(let v)? = self.traceData else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Confidence_Telemetry_V1_LibraryTraces.Trace, rhs: Confidence_Telemetry_V1_LibraryTraces.Trace) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.traceData != rhs.traceData {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Confidence_Telemetry_V1_LibraryTraces.Trace.CountTrace: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Confidence_Telemetry_V1_LibraryTraces.Trace.protoMessageName + ".CountTrace"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Confidence_Telemetry_V1_LibraryTraces.Trace.CountTrace, rhs: Confidence_Telemetry_V1_LibraryTraces.Trace.CountTrace) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Confidence_Telemetry_V1_LibraryTraces.Trace.RequestTrace: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Confidence_Telemetry_V1_LibraryTraces.Trace.protoMessageName + ".RequestTrace"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}millisecond_duration\0\u{1}status\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.millisecondDuration) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.millisecondDuration != 0 {
      try visitor.visitSingularUInt64Field(value: self.millisecondDuration, fieldNumber: 1)
    }
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Confidence_Telemetry_V1_LibraryTraces.Trace.RequestTrace, rhs: Confidence_Telemetry_V1_LibraryTraces.Trace.RequestTrace) -> Bool {
    if lhs.millisecondDuration != rhs.millisecondDuration {return false}
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Confidence_Telemetry_V1_LibraryTraces.Trace.RequestTrace.Status: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STATUS_UNSPECIFIED\0\u{1}STATUS_SUCCESS\0\u{1}STATUS_ERROR\0\u{1}STATUS_TIMEOUT\0\u{1}STATUS_CACHED\0")
}

extension Confidence_Telemetry_V1_LibraryTraces.Trace.EvaluationTrace: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Confidence_Telemetry_V1_LibraryTraces.Trace.protoMessageName + ".EvaluationTrace"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}evaluation_reason\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.evaluationReason) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.evaluationReason != .unknown {
      try visitor.visitSingularEnumField(value: self.evaluationReason, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Confidence_Telemetry_V1_LibraryTraces.Trace.EvaluationTrace, rhs: Confidence_Telemetry_V1_LibraryTraces.Trace.EvaluationTrace) -> Bool {
    if lhs.evaluationReason != rhs.evaluationReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Confidence_Telemetry_V1_LibraryTraces.Trace.EvaluationTrace.EvaluationReason: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0EVALUATION_REASON_UNKNOWN\0\u{1}EVALUATION_REASON_SUCCESS\0\u{1}EVALUATION_REASON_STALE\0\u{1}EVALUATION_REASON_FLAG_NOT_FOUND\0\u{1}EVALUATION_REASON_TYPE_MISMATCH\0\u{1}EVALUATION_REASON_ERROR\0")
}
